name: adbot
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#from here to the end copy the code and replace it with your previous code (version 3.7.0)

version: 3.7.0+38

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  flutter_svg:
  http:
  get_storage:
  flutter_spinkit: 5.2.0
  speech_to_text:
  flutter_tts: ^3.6.3
  firebase_auth: ^4.6.3
  #  google_mobile_ads:
  google_sign_in: ^6.1.4
  the_apple_sign_in: ^1.1.1
  saver_gallery: ^2.0.1
  permission_handler: ^10.2.0
  device_info_plus: ^9.0.2
  dio:
  share_plus:
  cloud_firestore: ^4.8.2
  webview_flutter:
  http_auth:
  flutter_stripe: ^9.2.2
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.1.0+1
  modal_progress_hud_nsn: 0.4.0
  firebase_storage: ^11.2.4
  image_picker: ^1.0.0
  flutter_sslcommerz: ^2.2.0-nullsafety.0
  pay: ^1.1.0
  unity_ads_plugin: ^0.3.8

  font_awesome_flutter: ^10.4.0
  flutter_paystack:
    git:
      url: https://github.com/appdevsx/flutter_paystack
      ref: master
  flutterwave_standard: 1.0.8
  uuid: ^3.0.7
  syncfusion_flutter_pdf:
  syncfusion_flutter_pdfviewer: 22.1.37
  path_provider: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
#  change_app_package_name: ^1.1.0
#  flutter_app_name: ^0.1.1
#  flutter_launcher_icons: ^0.13.1
#
#flutter_app_name:
#  name: "AdBot"   # >> Set AppName First

dependency_overrides:
  webview_flutter: ^4.2.0
  http: 1.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Logo/
    - assets/apple_pay.json
    - assets/google_pay.json
    - assets/icon/
    - assets/icon/diet_chart.svg

#end version 3.7.0